[[Uno]]
arch = "aarch64"
git-tree-sha1 = "71d273d5002445dc25de9ce5cf3e89055bc3d6a9"
libgfortran_version = "5.0.0"
os = "macos"

    [[Uno.download]]
    sha256 = "0699a65994e450243f41c58be368c4a93c1acbd416d26abe5dc5dd1e5f26f13b"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Uno]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e2cf1d65f2e84db4ce96dbd9566abda8877c6ed"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "847ecfc1daf60748eeb16ca9444ae3c1402c0397627a28ee40bdb4f8abefc7a1"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ff79db0cda870dae527ed3e8f8c8cba4768766a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "209ea60a847794f79036df66d90b5593eb7ad93dfcc194aeb482a753e6fadb30"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0bca8905bf8afe735833ea1d40991aafae7fba7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "49379bc2b792c06dad23216938a1927f1814560e8bd0234c9e600e1fca649728"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15671d426b7a1a832368e8f8fc6dcd1bfb4b28f6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "6004984f32d3da40123350a07a6d9ee8d788dc757594f64066c95c4328a69668"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70ec7d4d07555b70fdfbe92300e22dab328f86e9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "1012125d0a36e025784a48368ddae87873710705a0663c906c39d3fa14148584"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c076e0e7dfa75e94ceef4dcba58d9e8fe5a008df"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "062b2649c64127057288b1caac0ac5ace38449e6c48c180996155cd51fbe8f78"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08f68785889bea489baa79c212ccceb055213ac4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "e199fbb48d06a0cf3123a51182873f0e7f620a0796b50f14c705679f14740fc2"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cf5a584300c136349926671126e154dc46e3426"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "2e0a4c6ac228216fce87b554bdcdebeda7db311c7c7c0453aef329c709cbc51d"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b3238fe9a1a8d6a784c33fba54da66e5c60155f"
libgfortran_version = "5.0.0"
os = "windows"

    [[Uno.download]]
    sha256 = "8a64d4170b4bc6a211efaea56d066c38d49c0c593fbb1b01cc8c44bd83c583fd"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
git-tree-sha1 = "df1797824756f38d2bcdc7565f4f27bad70517dd"
libgfortran_version = "5.0.0"
os = "macos"

    [[Uno.download]]
    sha256 = "1b3e8e5a0b469861ad1547ed302abee85b17d8b01d8d4ed0c14ab79c712b6375"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "faa271a4ac0ba892a802225dff54e5ae4ccd1b0f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "99df408f0b7976d5c778dc39dccbb61d0924209c382575b6b262ee6564c533ab"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a70a426d79bbbf64a87a3b84bc820d36d9d4b1c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "ea9124325db7cc881531ca7559d34107428e8cc1edd7044a7e0eb16307fe786f"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
git-tree-sha1 = "9266d6c7d032f060d01b392069e7348e793aa6a5"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Uno.download]]
    sha256 = "c32d9f4305b55268f316e8e333be0ea4bf0e750abad146340223a527de0f79c9"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf0dfb600dd4157ead68ee6eb070cb5bc0339aa1"
libgfortran_version = "5.0.0"
os = "windows"

    [[Uno.download]]
    sha256 = "8e5fc21db864728cd259349fd1344f5f74735072333d071ce5ee4b2ea1f283d1"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.4+0/Uno.v2.7.4.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
