[[Uno]]
arch = "aarch64"
git-tree-sha1 = "8a44398db91a2771950905ccce8fdc928cfd9e94"
libgfortran_version = "5.0.0"
os = "macos"

    [[Uno.download]]
    sha256 = "18717c99d6f24d56580868b71e2c8a7fd75dff99dc554678fd353be6ab76a91c"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Uno]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67fb20bfcaf8908355577435d60689b9300adc23"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "ff93c6bae5f59e4b34e683bf88c780d25d8484541b6bb57860d0f99184286696"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9374de2134695dcd11444009fe83f8182be2313"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "fd447670ad85dd0c772b98924fb6898b53c225f2a1bcc92a3101c7c5c34bd781"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d882277ce45cd8f93592d89dfb45cff2f94550e8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "4e29abf285e688f6dd327336c9fbfcbdb1663411bf2c2bb7d48e0728926dc371"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a74ca77955ff13f13faddddbd610958420899de"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "0555691ad2b65d15ab5dcf821089f84a406e28f7d2e15c9518c446c5d1f7046b"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a617d3d2eb60d61f2cc9aecf6a28b770f61a0a7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "5c3cf3e49d2b44cee70caa828f837d196c5153a9430353182ef63be62eb3edc7"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c1f23ebd97c2495222fdbb6e3cf0e76a8bdc8f7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "7e697f47bb869ddaa107729f743b01de085bd4fe22f026ee04b0f828ad4a34dd"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc4f8780255e2678afae098d7e8ce1d56727aa2f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "8b73e66782155acf485d46e93bd73b186907aed87d76c503da576b0b27c813d7"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae719b481bddea9c46daeccced8774f2c0441a96"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "8f6b86c652b5cb47fe29c72908c51bcf4d84eca57c1e20e951c877168a95276e"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1baf6658aea76e52eadb35833d8dc6f36cc880d7"
libgfortran_version = "5.0.0"
os = "windows"

    [[Uno.download]]
    sha256 = "5edacdfc3e1fb75c78ee384a5837c93ec9d20bbfc8be38a8235dc6c94a689d65"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
git-tree-sha1 = "05d79fcd43d2f55166a35500f1768b5d1e18ce46"
libgfortran_version = "5.0.0"
os = "macos"

    [[Uno.download]]
    sha256 = "dbaa293af12df8b87046ba2e506eda8fc2e397418bc68bdbbd8faea96d3a659d"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bc968855fee024004c6d19134ff90c3d4c692b3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "3563646773495f8bc7e4cf146f99771c0c7e2d5cca73ab6ec19ee2cdc1d70fe0"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bf83199424370b6588d7028280f941a22167212"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "9194be9987e892031f41dc4df4705b8d0795766b5a3dd02b0b9e545a52a034ca"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
git-tree-sha1 = "679db16902e3473bef7687359c3ee537344988db"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Uno.download]]
    sha256 = "5afe91a5d2ba4621d4757366ada6061dab97d2955fb1e97eedaeddec11d4bf18"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "accdd881bb5d0838396afcfffc17a4ffa1ab8d1b"
libgfortran_version = "5.0.0"
os = "windows"

    [[Uno.download]]
    sha256 = "a7e27c9ef0c60b3def4712c20014d0ec401aa1e55e79f3b28e10b982af1646c7"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.9.0+0/Uno.v2.9.0.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
