[[Uno]]
arch = "aarch64"
git-tree-sha1 = "5919675fcf8a5b5981bbc7f88807b821877d5708"
libgfortran_version = "5.0.0"
os = "macos"

    [[Uno.download]]
    sha256 = "e7bb94004aa4220c5adae71fec7c86fed2c3617d1ba2a897787ebf0d61dc1d57"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Uno]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ac38f0a43c2759770734600c2bb2c27e4893109"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "b3de828e137c0c5039ab1985b92908ce412db8343be61ef3f609a04093c9b7d9"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b16cabb4c255f4821475b13c3f8e0a1b905a909"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "f316d47404730e3af0714418d72895d1cdec78907847ac35bcbccadb1ccc7148"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01c29d4f73da62a28a8f16672966738c0f6cbdb0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "82a239cb8972919f27d84181ecf2d3c71b6b88cd8c9bcd458ccc72836da03708"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c654a00b782321ee1735fb36fb53477752f501c3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "3dd73fafad9f8196b4454995137b85854ba6b8ff08b0ab59b69411145133d9b3"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a401e543c472f95348185aec55e958f72cac6c1a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "b51c9d93ad9fefbc64ac53d6c98dd5dfb48efe4c67488c373609130f7ba83820"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d51478cafec832804b1e40a1ee764e64878ad28"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "e7ae1b6c378777ddb67766804c31ae60a7fcaef9e950d3a5efa52678cb375f6f"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d28b083515fa9c7cef6b78f85662b614dae48900"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "9ca0b98c0d1a39c0868d194225b539829e1a9e69f1f87a3698c8c1af767b7e20"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ba731a5724e6452f6dde389b0bd4193f5e0104b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "15a8b9e23e02021d2d64abdf48a8a6e04f9cad6a948e1cae99a158cb66c7765d"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dfd7afaf5486ca6bb04d5eba0beb80734774719"
libgfortran_version = "5.0.0"
os = "windows"

    [[Uno.download]]
    sha256 = "8fe1d3ab8d738a41cd0d6d557f45897ce8ea171c8adfeb1e8fe26f396108f662"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
git-tree-sha1 = "33de65c80d01745cf534ff384d6718c7fd253820"
libgfortran_version = "5.0.0"
os = "macos"

    [[Uno.download]]
    sha256 = "fa8bbac3d0aaec8a4b0b8512d208d3ca1c96b0416aed207d0ff8b63188a2f4f9"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d96eaf82081b6c5fa39c751b962131fde8753830"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "eefbb5f5e334d517483cbebd47807981b5ea5c5df5c01a46f588818616e9ad0a"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bf907d34ac0ea0070fb85d0acc3c77bbf728404"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "4a2ffc3657ba6778d00ab87665608154af9a80862750d6433f830b84bff21b3e"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
git-tree-sha1 = "97f97b73c704f33e117df0b1b52182dc37b55687"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Uno.download]]
    sha256 = "10c62d5f29ccf07aecba456a2ce758f093445dd40977931d87873bf3cf606846"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd2c761e7ae82a3e7587beac9b602c01520bd763"
libgfortran_version = "5.0.0"
os = "windows"

    [[Uno.download]]
    sha256 = "2aa486ffc5b24fdc001d4a8bdb45b5ea8b8dbd49421544b0a21822ee05cc420f"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.7.5+0/Uno.v2.7.5.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
