# Autogenerated wrapper script for Uno_jll for aarch64-apple-darwin-libgfortran5
export amplexe, libuno, libuno_a

using HiGHS_jll
using HSL_jll
using METIS_jll
using ASL_jll
using MUMPS_seq_jll
using libblastrampoline_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("Uno")
JLLWrappers.@declare_library_product(libuno, "@rpath/libuno.dylib")
JLLWrappers.@declare_executable_product(amplexe)
JLLWrappers.@declare_file_product(libuno_a)
function __init__()
    JLLWrappers.@generate_init_header(HiGHS_jll, HSL_jll, METIS_jll, ASL_jll, MUMPS_seq_jll, libblastrampoline_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libuno,
        "lib/libuno.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        amplexe,
        "bin/uno_ampl",
    )

    JLLWrappers.@init_file_product(
        libuno_a,
        "lib/libuno.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
