# Autogenerated wrapper script for Uno_jll for x86_64-unknown-freebsd
export amplexe

using HSL_jll
using METIS_jll
using ASL_jll
using MUMPS_seq_jll
using libblastrampoline_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("Uno")
JLLWrappers.@declare_executable_product(amplexe)
function __init__()
    JLLWrappers.@generate_init_header(HSL_jll, METIS_jll, ASL_jll, MUMPS_seq_jll, libblastrampoline_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_executable_product(
        amplexe,
        "bin/uno_ampl",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
